# Generated by Django 5.2 on 2025-04-13 01:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('points', models.PositiveIntegerField(default=0)),
                ('transactions', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DrinkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Drink Type')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Flavor')),
            ],
        ),
        migrations.CreateModel(
            name='Merch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Merch')),
                ('size', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Milk Type')),
            ],
        ),
        migrations.CreateModel(
            name='PastryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Pastry Type')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.PositiveIntegerField(choices=[(1, 'Small'), (2, 'Medium'), (3, 'Large')], default=1)),
                ('extra_shots', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('whip_cream', models.BooleanField(default=False)),
                ('drink_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.drinktype')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.flavor')),
                ('milk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.milk')),
            ],
            options={
                'verbose_name': 'Drink Order',
                'verbose_name_plural': 'Drink Orders',
                'ordering': ['drink_type__name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Pastry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_warm', models.BooleanField(default=False)),
                ('pastry_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.pastrytype')),
            ],
            options={
                'verbose_name': 'Pastry Order',
                'verbose_name_plural': 'Pastry Orders',
                'ordering': ['pastry_type__name'],
            },
        ),
    ]
